-- 생산일자 2022년 5월
-- > 식품id, 식품 이름, 총 매출
-- 총 매출 desc, 식품id asc
SELECT FP.PRODUCT_ID
      ,FP.PRODUCT_NAME
      ,FP.PRICE * SUM(FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
    JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE BETWEEN '2022-05-01 00:00:00' AND '2022-05-31 23:59:59'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC
