WITH SUB AS (
    SELECT MEMBER_ID, COUNT(*) AS CNTS
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT MP.MEMBER_NAME
      ,RR.REVIEW_TEXT
      ,DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
    JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (SELECT MEMBER_ID
                    FROM SUB
                    WHERE CNTS = (SELECT MAX(CNTS) FROM SUB))
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
