-- 연도 ASC, YEAR_DEV ASC
-- 1) 분화 연도별 가장 큰 대장균 크기
-- 2) 편차 구하기
-- 3) 정렬
SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR
      ,YM.MAX_COLONY - ED.SIZE_OF_COLONY AS YEAR_DEV
      ,ED.ID
FROM ECOLI_DATA ED
    JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR_SUB
                ,MAX(SIZE_OF_COLONY) AS MAX_COLONY
          FROM ECOLI_DATA
          GROUP BY YEAR_SUB) YM
      ON YEAR(ED.DIFFERENTIATION_DATE) = YM.YEAR_SUB
ORDER BY YEAR ASC, YEAR_DEV ASC
