SELECT P.PRODUCT_CODE
      ,P.PRICE * SUM(OS.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE OS
    JOIN PRODUCT P ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC
