-- 7월 총 주문량+상반기 총 주문량
-- 값이 큰 순서대로 
-- 상위 3개
SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
    LEFT JOIN JULY ON FH.FLAVOR = JULY.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY FH.TOTAL_ORDER + SUM(JULY.TOTAL_ORDER) DESC
LIMIT 3
