-- 세단 or suv : O
-- 2022.11.1-2022.11.30 대여 가능 : O
-- 30일간의 대여 금액이 50 이상 200 미만
-- >자동차 id, 종류, 대여금액(fee)
-- 대여금액 desc, 종류 asc, id desc

WITH CAR_LIST AS (
    SELECT CRCC.CAR_ID
          ,CRCC.CAR_TYPE
          ,CRCC.DAILY_FEE
          ,MAX(CRCRH.END_DATE)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
        JOIN CAR_RENTAL_COMPANY_CAR AS CRCC ON CRCRH.CAR_ID = CRCC.CAR_ID
    WHERE CRCC.CAR_TYPE IN ('세단', 'SUV')
    GROUP BY CRCRH.CAR_ID
    HAVING MAX(CRCRH.END_DATE) < '2022-11-01 00:00:00'
), CAR_WITH_30DAYS_DC AS (
     SELECT CL.*
           ,DC_RATE.DISCOUNT_RATE
     FROM CAR_LIST AS CL
         JOIN (SELECT *
               FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
               WHERE CAR_TYPE IN ('세단', 'SUV')
                 AND DURATION_TYPE = '30일 이상') AS DC_RATE
          ON CL.CAR_TYPE = DC_RATE.CAR_TYPE
), CAR_WITH_FEE AS (
    SELECT *
          , DAILY_FEE * (1-DISCOUNT_RATE/100) * 30 AS FEE
    FROM CAR_WITH_30DAYS_DC
)

SELECT CAR_ID
      ,CAR_TYPE
      ,ROUND(FEE) AS FEE
FROM CAR_WITH_FEE
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
