WITH SUB AS (
    SELECT USER_ID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
)


SELECT YEAR(OS.SALES_DATE) AS YEAR
      ,MONTH(OS.SALES_DATE) AS MONTH
      ,S.GENDER AS GENDER
      ,COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS
    JOIN SUB S ON OS.USER_ID = S.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), S.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC
