SELECT HD.DEPT_ID
      ,HD.DEPT_NAME_EN
      ,DS.AVG_SAL
FROM (SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
      FROM HR_EMPLOYEES
      GROUP BY DEPT_ID) AS DS
        JOIN HR_DEPARTMENT AS HD ON DS.DEPT_ID = HD.DEPT_ID
ORDER BY DS.AVG_SAL DESC
