-- 2022년 1월 판매 데이터 기준 : 저자 별, 카테고리 별 매출액
-- > 저자 id, 저자명, 카테고리, 매출액
-- 저자id asc, 카테고리 desc

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
      ,SUM(B.PRICE*BS.SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01 00:00:00' AND '2022-01-31 23:59:59'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC
