 -- > 세단 중, 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트 출력
 -- 중복 X
 -- 자동차 ID DESC
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_CAR
              WHERE CAR_TYPE = '세단')
  AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC
