WITH TB1 AS ( -- 대여 기록 전체 + 대여 기간 타입 추출
    SELECT CRCRH.*
          ,CRCC_TR.DAILY_FEE
          ,DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 AS RENTAL_DATE
          ,CASE
            WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
            WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
            WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 90 THEN '90일 이상'
           END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
        JOIN (SELECT CAR_ID, DAILY_FEE
              FROM CAR_RENTAL_COMPANY_CAR
              WHERE CAR_TYPE = '트럭') CRCC_TR
        ON CRCRH.CAR_ID = CRCC_TR.CAR_ID
), TB2 AS ( -- TB1의 정보 + 할인율
    SELECT TB1.*
          ,IF(CRCDP_TR.DISCOUNT_RATE IS NULL, 0, CRCDP_TR.DISCOUNT_RATE) AS DISCOUNT_RATE
    FROM TB1
        LEFT JOIN (SELECT DURATION_TYPE, DISCOUNT_RATE
              FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
              WHERE CAR_TYPE = '트럭') CRCDP_TR
        ON TB1.DURATION = CRCDP_TR.DURATION_TYPE
)

-- 구하고자 하는 것
SELECT HISTORY_ID
      ,ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * RENTAL_DATE) AS FEE
FROM TB2
ORDER BY FEE DESC, HISTORY_ID DESC


-- #2 TB1의 CASE문을 좀 더 간단하게
WITH TB1 AS (
    SELECT *
          ,CASE
            WHEN CR.RENTAL_DUR >= 90 THEN '90일 이상'
            WHEN CR.RENTAL_DUR >= 30 THEN '30일 이상'
            WHEN CR.RENTAL_DUR >= 7  THEN '7일 이상'
            ELSE NULL
           END AS DURATION
    FROM (SELECT CRCRH.*
                ,DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 AS RENTAL_DUR
                ,CRCC_TR.DAILY_FEE
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
            JOIN (SELECT CAR_ID, DAILY_FEE
                  FROM CAR_RENTAL_COMPANY_CAR
                  WHERE CAR_TYPE = '트럭') CRCC_TR
            ON CRCRH.CAR_ID = CRCC_TR.CAR_ID) AS CR
), TB2 AS (
    SELECT TB1.*
          ,IF(CRCDP_TR.DISCOUNT_RATE IS NULL, 0, CRCDP_TR.DISCOUNT_RATE) AS DISCOUNT_RATE
    FROM TB1
        LEFT JOIN (SELECT DURATION_TYPE, DISCOUNT_RATE
              FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
              WHERE CAR_TYPE = '트럭') CRCDP_TR
        ON TB1.DURATION = CRCDP_TR.DURATION_TYPE
)

SELECT HISTORY_ID
      ,ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * RENTAL_DUR) AS FEE
FROM TB2
ORDER BY FEE DESC, HISTORY_ID DESC
