WITH SUB AS (
    SELECT H.*
                 ,CC.CHALLENGES_CREATED
    FROM HACKERS H
        JOIN (SELECT HACKER_ID
                                ,COUNT(*) AS CHALLENGES_CREATED
                  FROM CHALLENGES
                  GROUP BY HACKER_ID) CC ON H.HACKER_ID = CC.HACKER_ID
)

SELECT *
FROM SUB
WHERE CHALLENGES_CREATED = (SELECT MAX(CHALLENGES_CREATED) FROM SUB)
        OR (CHALLENGES_CREATED < (SELECT MAX(CHALLENGES_CREATED) FROM SUB) 
                AND CHALLENGES_CREATED IN (SELECT CHALLENGES_CREATED FROM SUB GROUP BY CHALLENGES_CREATED HAVING COUNT(*) = 1))
ORDER BY CHALLENGES_CREATED DESC, HACKER_ID ASC
