-- 조회수 Top1 게시글에 대한 첨부파일 경로 조회
-- file id desc
-- 파일 경로+파일이름(id+name+ext)
SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS UGB
    JOIN USED_GOODS_FILE AS UGF ON UGB.BOARD_ID = UGF.BOARD_ID
WHERE UGB.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_EXT DESC
