-- RARE인 아이템들의 다음 업그레이드 아이템
-- ID, NAME, RARITY
-- ID DESC
WITH ITEM_UPG AS (
    SELECT INFO.*
          ,IT.PARENT_ITEM_ID
          ,IT.ITEM_ID AS UPG_ITEM
    FROM (SELECT *
          FROM ITEM_INFO
          WHERE RARITY = 'RARE') AS INFO
        JOIN ITEM_TREE AS IT ON INFO.ITEM_ID = IT.PARENT_ITEM_ID
)

SELECT ITEM_ID
      ,ITEM_NAME
      ,RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT UPG_ITEM FROM ITEM_UPG)
ORDER BY ITEM_ID DESC
