-- 2021년 출판, 인문
-- 아이디, 출판일 출력
-- 출판일 ASC
SELECT BOOK_ID
      ,DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK 
WHERE PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31'
  AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC
