-- 완료된 중고거래
-- 총금액 >= 70
-- 회원id, 닉네임, 총거래금액
-- 총거래금액 asc
SELECT UGB.WRITER_ID AS USER_ID
      ,UGU.NICKNAME
      ,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UGB
    JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGB.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC
